using System;
using System.Collections.Generic;
using System.Text;

namespace endiffo.Search
{
    /// <summary>
    /// The search interface requires both a result generation and result writing method. This allows muliple searches that are entirely different to be processed in the same queue.
    /// </summary>
    internal interface ISearch
    {
        /// <summary>
        /// Perform the search against the system as required and generate results, storing them within the class for future use.
        /// </summary>
        void GenerateResults();

        /// <summary>
        ///Take the results generated by <see cref="GenerateResults"/> and prepare them for writing to disk. Serialisation to Json is the most obvious choice for many scenarios. 
        /// </summary>
        /// <returns>A string representation of the results</returns>
        string WriteResults();
    }
}
